apps/field/urls.py
from django.urls import path

from apps.field import views

urlpatterns = [
    path('list/', views.FieldListView.as_view(), name='field-list'),
    path('get-varieties/<str:crop_code>/', views.get_varieties, name='get_varieties'),
    path('create/', views.FieldCreateView.as_view(), name='field-create'),
    path('<int:pk>/update/', views.FieldUpdateView.as_view(), name='field-update'),
#     path('<int:pk>/update/', views.fieldUpdateView, name='field-update'),
    path('<int:pk>/detail/', views.FieldDetailView.as_view(), name='field-detail'),
    path('<int:pk>/delete/', views.FieldDeleteView.as_view(), name='field-delete'),
    path('csv_field_create/', views.CsvFieldCreateView.as_view(), name='csv-field-create'),
    path('csv_field_mapping/<int:pk>', views.CsvFieldMappingView.as_view(), name='csv-field-mapping'),
    path('read_shape_file/', views.ReadShapeFile.as_view(), name='read_shape_file'),
    path('save_shape_file/', views.SaveShapeFile.as_view(), name='save-shape-file'),
    path('get_coordinates/', views.GetCoordinates.as_view(), name='get-coordinates'),
    path('eos-create-task/', views.EosCreateTask.as_view(), name='eos-create-task'),
    path('eos-task-status/', views.EosTaskStatus.as_view(), name='eos-task-status'),
    path('eos-task-search/', views.EosSearchTask.as_view(), name='eos-task-search'),
    path('eos-soilmoisture-create-task/', views.EosSoilmoistureCreateTask.as_view(),
         name='eos-soilmoisture-create-task'),
    path('eos-soilmoisture-data/', views.EosSoilMoistureData.as_view(), name='eos-soilmoisture-data'),
    path('eos-download-visual-data-create-task/', views.EosDownloadVisualDataCreateTask.as_view(),
         name='eos-download-visual-data-create-task'),
    path('field_location_map/vegetation/<int:pk>', views.FieldLocationMapVegetation.as_view(),
         name='field-location-map-vegetation'),
    path('field_location_map/moisture/<int:pk>', views.FieldLocationMapMoisture.as_view(),
         name='field-location-map-moisture'),
    path('EosTestTask/', views.EosTestTask.as_view(), name='EosTestTask'),
    path('eos-create-task-for-date-list/', views.EosCreateTasksForDateList.as_view(),
         name='eos-create-task-for-date-list'),
     #
     path('test/',views.test, name = 'test'),
     path('fieldActivity/',views.fieldActivity, name = 'fieldActivity'),
     path('fieldActivity_delete/<int:pk>',views.fieldActivity_delete, name = 'fieldActivity-delete'),
     path('upload_field_vegetation_csv',views.upload_field_vegetation_csv, name = 'upload_field_vegetation_csv'),
     path('field_csv_download',views.field_csv_download, name = 'field_csv_download'),
     # 19-06-23
     path('field_data_update/',views.field_data_update, name = 'field_data_update'),
     # 13-12-24
     path('update_field_2024/<str:pk>',views.update_field_2024, name = 'update_field_2024'),

]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .api_urls import router
from apps.accounts.forms import LoginForm
# from apps.accounts.views import AccountLoginView
from apps.accounts.views import *


# handler404_account = 'apps.accounts.views.handler404_account'
# handler500_account = 'apps.accounts.views.handler500_account'
# handler404 = 'apps.growerpayments.views.error404_payment'
# handler500 = 'apps.growerpayments.views.error500_payment'


urlpatterns = [
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms_and_conditions, name='terms_and_conditions'),
    path('', main_page, name='main_page'),
    
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('login/', AccountLoginView.as_view(
        redirect_authenticated_user=True,
        template_name='registration/login.html',
        authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/passowrd_reset_email_format.html',
             success_url='/password-reset/done/'
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    path('accounts/', include('apps.accounts.urls')),
    path('farms/', include('apps.farms.urls')),
    path('field/', include('apps.field.urls')),
    path('gallery/', include('apps.gallery.urls')),
    path('grower/',include('apps.grower.urls')),
    path('survey/', include('apps.survey.urls')),
    path('growersurvey/', include('apps.growersurvey.urls')),
    path('notesandupdate/', include('apps.notesandupdate.urls')),
    path('documents/', include('apps.documents.urls')),
    path('contracts/', include('apps.contracts.urls')),
    # sdp
    path('storage/', include('apps.storage.urls')),
    path('processor/', include('apps.processor.urls')),
    path('chat/', include('apps.chat.urls')),
    path('farmsmart/', include('apps.farmsmart.urls')),
    path('growerpayments/', include('apps.growerpayments.urls')),
    path('processor2/', include('apps.processor2.urls')),
    path('processor3/', include('apps.processor3.urls')),
    path('processor4/', include('apps.processor4.urls')),
    path('assistantapp/', include('apps.assistantapp.urls')),
    path('tracemodule/', include('apps.tracemodule.urls')),
    path('warehouse/', include('apps.warehouseManagement.urls')),
    path('quickbooks/', include('apps.quickbooks_integration.urls')),  

    path("select2/", include("django_select2.urls")),  
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Agreeta Solutions (AgFarm Admin Panel)'

apps/field/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.utils import timezone
from apps.contracts.models import SignedContracts
from apps.farms.models import Farm
from apps.grower.models import Grower, Consultant
from apps.storage.models import Storage, ShapeFileDataCo as storageshapfile
from apps.growersurvey.models import SustainabilitySurvey,TypeSurvey,NameSurvey
from apps.documents.models import DocumentFile, DocumentFolder

from .choices import CHOICE
from django.contrib.postgres.fields import ArrayField, JSONField

class Crop(models.Model):
    name = models.CharField(max_length=100, unique=True) 
    code = models.CharField(max_length=10, unique=True, editable=False)  

    def save(self, *args, **kwargs):        
        if self.name:
            self.code = self.name.upper()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class CropVariety(models.Model):
    crop = models.ForeignKey(Crop, on_delete=models.CASCADE, related_name="cropVariety")
    variety_name = models.CharField(max_length=255, null=True, blank=True)
    variety_code = models.CharField(max_length=255, null=True, blank=True)

    def save(self, *args, **kwargs):        
        if self.variety_name:
            self.variety_code = self.variety_name 
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.crop.code} - {self.variety_name}"

class CropType(models.Model):
    crop = models.ForeignKey(Crop, on_delete=models.CASCADE, related_name="cropType")
    type = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"{self.crop.name} - {self.type}"


class Field(models.Model):
    """Database model for field"""  
    @staticmethod
    def crop_choices():
        crops = Crop.objects.all()
        return [(crop.code, crop.name) for crop in crops] 
    
    @staticmethod
    def variety_choices():
        varieties = CropVariety.objects.all()
        return [(variety.variety_code, variety.variety_name) for variety in varieties] 
    
    name = models.CharField(unique=True, max_length=200)
    farm = models.ForeignKey(
        'farms.Farm', on_delete=models.CASCADE, related_name='fields'
    )
    grower = models.ForeignKey(
        'grower.Grower', on_delete=models.CASCADE)
    batch_id = models.IntegerField(null=True, blank=True)
    acreage = models.FloatField()
    fsa_farm_number = models.CharField(
        max_length=250,help_text="Multiple values can be Comma (,) separated", null=True, blank=True,
        verbose_name='FSA Farm Number')
    fsa_tract_number = models.CharField(
        max_length=250,help_text="Multiple values can be Comma (,) separated", null=True, blank=True,
        verbose_name='FSA Tract Number')
    fsa_field_number = models.CharField(
        max_length=250,help_text="Multiple values can be Comma (,) separated", null=True, blank=True,
        verbose_name='FSA Field Number')
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    crop = models.CharField(max_length=255, choices=[], null=True, blank=True)
    variety = models.CharField(
        max_length=255, choices=[], null=True, blank=True
    )
    yield_per_acre = models.FloatField(null=True, blank=True, verbose_name='Yield Per Acre')
    total_yield = models.FloatField(null=True, blank=True, verbose_name='Total Yield')
    crop_tech = models.CharField(max_length=200, blank=True, null=True, verbose_name='Crop Tech')
    burndown_chemical = models.CharField(
        max_length=200, blank=True, null=True, verbose_name='Burndown Chemical'
    )
    burndown_chemical_date = models.DateField(
        null=True, blank=True, verbose_name='Burndown Chemical Date'
    )
    plant_date = models.DateField(null=True, blank=True, verbose_name='Plant Date')
    preemergence_chemical = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Preemergence Chemical'
    )
    preemergence_chemical_date = models.DateField(
        null=True, blank=True,
        verbose_name='Preemergence Chemical Date'
    )
    stand_count = models.IntegerField(null=True, blank=True, verbose_name='Stand Count')
    emergence_date = models.DateField(
        null=True, blank=True, verbose_name='Emergence Date'
    )
    post_emergence_chemical_1 = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Post Emergence Chemical 1'
    )
    post_emergence_chemical_1_date = models.DateField(
        null=True, blank=True,
        verbose_name='Post Emergence Chemical 1 Date'
    )
    post_emergence_chemical_2 = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Post Emergence Chemical 2'
    )
    post_emergence_chemical_2_date = models.DateField(
        null=True, blank=True,
        verbose_name='Post Emergence Chemical 2 Date'
    )
    post_emergence_chemical_3 = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Post Emergence Chemical 3'
    )
    post_emergence_chemical_3_date = models.DateField(
        null=True, blank=True,
        verbose_name='Post Emergence Chemical 3 Date'
    )
    post_emergence_chemical_4 = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Post Emergence Chemical 4'
    )
    post_emergence_chemical_4_date = models.DateField(
        null=True, blank=True, verbose_name='Post Emergence Chemical 4 Date'
    )
    flood_date = models.DateField(
        null=True, blank=True, verbose_name='Flood Date'
    )
    awd_drydown_date = models.DateField(
        null=True, blank=True, verbose_name='AWD Dry Down Date'
    )
    fungicide_micronutrients = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Fungicide Micronutrients'
    )
    fungicide_micronutrients_date = models.DateField(
        null=True, blank=True, verbose_name='Fungicide Micronutrients Date'
    )
    insecticide_application = models.CharField(
        max_length=100, blank=True, null=True,
        verbose_name='Insecticide Application'
    )
    insecticide_application_date = models.DateField(
        null=True, blank=True,
        verbose_name='Insecticide Application Date'
    )
    drain_date = models.DateField(null=True, blank=True, verbose_name='Drain Date')
    sodium_chlorate_date = models.DateField(
        null=True, blank=True,
        verbose_name='Sodium Chlorate Date'
    )
    harvest_date = models.DateField(
        null=True, blank=True, verbose_name='Harvest Date'
    )
    soil_sample_date = models.DateField(
        null=True, blank=True, verbose_name='Soil Sample Date'
    )
    litter = models.CharField(max_length=100, blank=True, null=True)
    pre_fert_rate = models.PositiveIntegerField(
        null=True, blank=True, verbose_name='Pre Fert Rate'
    )
    pre_fert_product = models.CharField(
        max_length=255, choices=CHOICE.FERT_PRODUCT_CHOICES,
        blank=True, null=True,
        verbose_name='Pre Fert Product'
    )
    early_post_fert_rate = models.PositiveIntegerField(
        null=True, blank=True, verbose_name='Early Post Fert Rate'
    )
    early_post_fert_product = models.CharField(
        max_length=255, choices=CHOICE.FERT_PRODUCT_CHOICES,
        blank=True, null=True,
        verbose_name='Early Post Fert Product'
    )
    early_post_fert_date = models.DateField(
        null=True, blank=True,
        verbose_name='Early Post_Fert Date'
    )
    foliar_fert_app_rate = models.FloatField(
        null=True, blank=True, verbose_name='Foliar Fert App Rate'
    )
    foliar_fert_app_product = models.CharField(
        max_length=100, choices=CHOICE.FERT_PRODUCT_CHOICES,
        blank=True, null=True,
        verbose_name='Foliar Fert App Product'
    )
    foliar_fert_app_date = models.DateField(
        null=True, blank=True,
        verbose_name='Foliar Fert App Date'
    )
    pre_flood_fert_rate = models.FloatField(
        null=True, blank=True,
        verbose_name='Pre Flood Fert Rate'
    )
    pre_flood_fert_product = models.CharField(
        max_length=255, choices=CHOICE.FERT_PRODUCT_CHOICES, 
        blank=True, null=True, verbose_name='Pre Flood Fert Product'
    )
    pre_flood_fert_date = models.DateField(
        null=True, blank=True,
        verbose_name='Pre Flood Fert Date'
    )
    post_flood_midseason_fert_rate = models.FloatField(
        null=True, blank=True,
        verbose_name='Post Flood Midseason Fert Rate'
    )
    post_flood_midseason_fert_product = models.CharField(
        max_length=255, choices=CHOICE.FERT_PRODUCT_CHOICES,
        blank=True, null=True, verbose_name='Post Flood Midseason Fert Product'
    )
    post_flood_midseason_fert_date = models.DateField(
        null=True, blank=True,
        verbose_name='Post Flood Midseason Fert Date'
    )
    post_flood_midseason_fert_rate2 = models.DateTimeField(
        null=True, blank=True,
        verbose_name='Post Flood Midseason Fert Rate 2'
    )
    post_flood_midseason_fert_product2 = models.CharField(
        max_length=255, choices=CHOICE.FERT_PRODUCT_CHOICES,
        blank=True, null=True,
        verbose_name='Post Flood Midseason Fert Product 2'
    )
    post_flood_midseason_fert_date2 = models.DateField(
        null=True, blank=True,
        verbose_name='Post Flood Midseason Fert Date 2'
    )
    post_flood_midseason_fert_rate3 = models.PositiveIntegerField(
        null=True, blank=True,
        verbose_name='Post Flood Midseason Fert Rate 3'
    )
    post_flood_midseason_fert_product3 = models.CharField(
        max_length=255, choices=CHOICE.FERT_PRODUCT_CHOICES,
        blank=True, null=True,
        verbose_name='Post Flood Midseason Fert Product 3'
    )
    post_flood_midseason_fert_date3 = models.DateField(
        null=True, blank=True,
        verbose_name='Post Flood Midseason Fert Date 3'
    )

apps/field/templates/field/field_create.html
{% extends "base.html" %}
{% load static %} {% block title %} Create Field {% endblock title %} 

{% block extrahead %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y3EWVPF7PQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y3EWVPF7PQ');
</script>
{% endblock extrahead %}

{% block content %}
{% include 'navbar.html' %}
<style>

select option:disabled{text-decoration: line-through; background-color: #ccc; font-style: italic;}
.bootstrap-select .dropdown-menu li.disabled.selected{display: none;}
.dropdown.bootstrap-select.form-control .btn{border: 1px solid #B2BEB5; padding: 13px 8px; border-radius:0;}
.bootstrap-select .dropdown-menu{max-width: 280px;}
.bootstrap-select .dropdown-menu li.selected.active .dropdown-item.active.selected{margin-left: 0;padding: 0;}
</style>
<div class="main-content">
    {% include 'header.html' %} {% load crispy_forms_tags %}
    <main>
        {% include '_alerts.html' %}
        <span class="farm headingtop">Create Field</span>
        
        <div class="card farm-fields-container">
            <div class="container-fluid">
                <form method="post" class="farm-fields-form" action="{% url 'test' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="input-group align-items-center custom-input-group">
                                <div class="input-group-prepend pe-1">
                                  <label for=""><strong>Select Crop Year</strong></label>
                                </div>
                                <select name="scrop_year" class="select form-control" id="scrop_year" required>
                                    <option value="" disabled>Select Crop Year</option>
                                    <option value="2024">2024</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <!-- <div class="col-md-4">
                            {{ form.farm|as_crispy_field }}
                        </div> -->
                        <div class="col-md-4">
                            <div id="div_id_farm" class="form-group">
                                <label for="id_farm" class=" requiredField">
                                    Farm<span class="asteriskField">*</span>
                                </label>
                                <div>
                                    <select name="farm" class="select form-control selectpicker" required="" id="id_farm" data-live-search="true">
                                        <option value="all" selected disabled>Select Farm</option>
                                        {% for frm in farms %}
                                        <option value="{{frm.id}}">{{frm.name}}-{{frm.id}}</option>
                                        {% endfor %}
                                    </select>

                                </div>

                            </div>
                        </div>
                        <!-- <div class="col-md-4">
                            {{ form.grower|as_crispy_field }}
                        </div> -->
                        <div class="col-md-4">
                            <div id="div_id_grower" class="form-group">
                                <label for="id_grower" class=" requiredField">
                                    Grower<span class="asteriskField">*</span>
                                </label>
                                <div>
                                    <select name="grower" class="select form-control disabled-consultants selectpicker" required="" id="id_grower" data-live-search="true">
                                        <option value="all" selected disabled>Select Grower</option>
                                        {% for gwdp in growers_dpdwn %}
                                        <option value="{{gwdp.id}}">{{gwdp.name}}-{{gwdp.id}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.batch_id|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.acreage|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.fsa_farm_number|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.fsa_tract_number|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.fsa_field_number|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.latitude|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.longitude|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.crop|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            <div id="div_id_variety" class="form-group">
                                <label for="id_variety" class=" requiredField">
                                    Variety<span class="asteriskField">*</span>
                                </label>
                                <div>
                                    <select name="variety" class="select form-control" required id="id_variety">
                                        <option value="">Select Variety</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            {{ form.yield_per_acre|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                            {{ form.total_yield|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                            {{ form.crop_tech|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                            {{ form.eschlon_id|as_crispy_field }}
                        </div>
                        
                    </div>
                    
                    <div class="row">
                        <div class="form-btn-row">
                            <a href="{% url 'field-list' %}" class="btn-close-cancel btn-space">Cancel</a>
                            <input type="submit" class="btn-save-submit" value="Continue">
                        </div>
                    </div>
            </div>
            </form>
    </main>
    {% include 'footer.html' %}
</div>
{% endblock %}
{% block jquery %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script
  src="https://code.jquery.com/jquery-3.6.3.min.js"
  integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
  crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        // Attach change event listener to the crop field
        $('#id_crop').change(function () {
            var cropCode = $(this).val();  // Get the selected crop code
            var varietySelect = $('#id_variety');  // Get the variety field

            // Clear current variety options
            varietySelect.empty();
            varietySelect.append('<option value="">Select Variety</option>');

            if (cropCode) {
                // Make an AJAX request to get the varieties for the selected crop
                $.ajax({
                    url: `/field/get-varieties/${cropCode}/`, // Django view URL
                    type: 'GET',
                    success: function (data) {
                        // Populate the variety dropdown with the returned data
                        $.each(data, function (index, variety) {
                            varietySelect.append('<option value="' + variety.id + '">' + variety.variety_name + '</option>');
                        });
                    },
                    error: function () {
                        console.log('Error loading crop varieties');
                    }
                });
            }
        });
    });
</script>

{% comment %} <script>
    $('#id_crop').on('change', function(e){
        $('#id_variety').val('');
        $('#id_variety').find('option').prop('disabled', false);
        var crop_val = $(this).val();
        if(crop_val == 'RICE')
        {
            $('#id_variety option').filter('[value="DG 2425 XF"],[value="DG 3450 B2XF"],[value="DG 3470 B3XF"],[value="DG 3570 B3XF"],[value="DG 3635 B2XF"],[value="DG 3544 B2XF"],[value="DG 3651NR B2XF"],[value="DG 3109 B2XF"],[value="DG 3387 B3XF"],[value="DG 3421 B3XF"],[value="DG H929 B3XF"],[value="DG 3555 B3XF"],[value="DG 3402 B3XF"],[value="DG H959 B3XF"],[value="DG 3469 B3XF"],[value="DG 3615 B3XF"],[value="DG P224 B3XF"],[value="DG 3385 B2XF"],[value="DG 3422 B3XF"],[value="DG 3799 B3XF"],[value="DG-Wheat"],[value="DG 1464"],[value="DG3605"],[value="DG 3215 B3XF"]').prop('disabled', true);
        }

        if(crop_val == 'COTTON')
        {
            $('#id_variety option').filter('[value="DG-263L"],[value="DG-Wheat"]').prop('disabled', true);
        }
        if(crop_val == 'WHEAT')
        {
            $('#id_variety option').filter('[value="DG-263L"],[value="DG 2425 XF"],[value="DG 3450 B2XF"],[value="DG 3470 B3XF"],[value="DG 3570 B3XF"],[value="DG 3635 B2XF"],[value="DG 3544 B2XF"],[value="DG 3651NR B2XF"],[value="DG 3109 B2XF"],[value="DG 3387 B3XF"],[value="DG 3421 B3XF"],[value="DG H929 B3XF"],[value="DG 3555 B3XF"],[value="DG 3402 B3XF"],[value="DG H959 B3XF"],[value="DG 3469 B3XF"],[value="DG 3615 B3XF"],[value="DG P224 B3XF"],[value="DG 3385 B2XF"],[value="DG 3422 B3XF"],[value="DG 3799 B3XF"],[value="DG 1464"],[value="DG3605"],[value="DG 3215 B3XF"]').prop('disabled', true);
        }
        if(crop_val == 'PEANUT')
        {
            $('#id_variety option').filter('[value="DG-263L"],[value="DG-Wheat"],[value="DG 2425 XF"],[value="DG 3450 B2XF"],[value="DG 3470 B3XF"],[value="DG 3570 B3XF"],[value="DG 3635 B2XF"],[value="DG 3544 B2XF"],[value="DG 3651NR B2XF"],[value="DG 3109 B2XF"],[value="DG 3387 B3XF"],[value="DG 3421 B3XF"],[value="DG H929 B3XF"],[value="DG 3555 B3XF"],[value="DG 3402 B3XF"],[value="DG H959 B3XF"],[value="DG 3469 B3XF"],[value="DG 3615 B3XF"],[value="DG P224 B3XF"],[value="DG 3385 B2XF"],[value="DG 3422 B3XF"],[value="DG 3799 B3XF"],[value="DG-Wheat"],[value="DG 1464"],[value="DG3605"],[value="DG 3215 B3XF"],[value="DG-263L"],[value="DG 2425 XF"],[value="DG 3450 B2XF"],[value="DG 3470 B3XF"],[value="DG 3570 B3XF"],[value="DG 3635 B2XF"],[value="DG 3544 B2XF"],[value="DG 3651NR B2XF"],[value="DG 3109 B2XF"],[value="DG 3387 B3XF"],[value="DG 3421 B3XF"],[value="DG H929 B3XF"],[value="DG 3555 B3XF"],[value="DG 3402 B3XF"],[value="DG H959 B3XF"],[value="DG 3469 B3XF"],[value="DG 3615 B3XF"],[value="DG P224 B3XF"],[value="DG 3385 B2XF"],[value="DG 3422 B3XF"],[value="DG 3799 B3XF"],[value="DG 1464"],[value="DG3605"],[value="DG 3215 B3XF"]').prop('disabled', true);
        }
    });
</script> {% endcomment %}
<script>
    $('#Farm-Configuration-active').addClass('activeLink');
                  
    $('#Farm-Configuration-down').addClass('down');
    $('#Farm-Configuration-sub').show();
    
    $('#Field-Management').addClass('activeLink active-nav');
    </script>
{% endblock jquery %}