apps/accounts/urls.py
from django.urls import path

from apps.accounts import views


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('user_create/', views.UserCreateView.as_view(), name='user-create'),
    path('account_list/', views.AccountListView.as_view(), name='account-list'),
    path('account/<int:pk>/update/', views.AccountUpdateView.as_view(), name='account-update'),
    path('account/<int:pk>/detail/', views.AccountDetailView.as_view(), name='account-detail'),
    path('account/<int:pk>/delete/', views.AccountDeleteView.as_view(), name='account-delete'),
    path('account/<int:pk>/emailresend/', views.EmailSendView.as_view(), name='email-resend'),
    path('account_create/', views.AccountCreateView.as_view(), name='account-create'),
    path('account_user/', views.account_user, name='account_user'),
    path('add_consultant/', views.ConsultantCreateView.as_view(), name='add-consultant'),
    path('user/', views.UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/update/', views.UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/detail/', views.UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user-delete'),
    path('role/create/', views.RoleCreateView.as_view(), name='role-create'),
    path('role/', views.RoleListView.as_view(), name='role-list'),
    path('role/<int:pk>/update/', views.RoleUpdateView.as_view(), name='role-update'),
    path('role/<int:pk>/delete/', views.RoleDeleteView.as_view(), name='role-delete'),
    path('super_account_create/', views.SuperAccountCreateView.as_view(), name='super-account-create'),
    #code
    path('change_password/', views.change_password, name='change_password'),
    path('user_change_password/<int:pk>', views.user_change_password, name='user_change_password'),
    path('show_notification_counter/', views.show_notification_counter, name='show_notification_counter'),
    path('show_notification/', views.show_notification, name='show_notification'),
    # 12-04-23
    path('show_log/', views.show_log, name='show_log'),
    # 16-06-23 
    path('grower_sign_up/', views.grower_sign_up, name='grower_sign_up'),
    path('userstate_change/', views.userstate_change, name='userstate_change'),

    path('version_update/', views.version_update, name='version_update'),
    path('version_update_list/', views.version_update_list, name='version_update_list'),
    
]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .api_urls import router
from apps.accounts.forms import LoginForm
# from apps.accounts.views import AccountLoginView
from apps.accounts.views import *


# handler404_account = 'apps.accounts.views.handler404_account'
# handler500_account = 'apps.accounts.views.handler500_account'
# handler404 = 'apps.growerpayments.views.error404_payment'
# handler500 = 'apps.growerpayments.views.error500_payment'


urlpatterns = [
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms_and_conditions, name='terms_and_conditions'),
    path('', main_page, name='main_page'),
    
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('login/', AccountLoginView.as_view(
        redirect_authenticated_user=True,
        template_name='registration/login.html',
        authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/passowrd_reset_email_format.html',
             success_url='/password-reset/done/'
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    path('accounts/', include('apps.accounts.urls')),
    path('farms/', include('apps.farms.urls')),
    path('field/', include('apps.field.urls')),
    path('gallery/', include('apps.gallery.urls')),
    path('grower/',include('apps.grower.urls')),
    path('survey/', include('apps.survey.urls')),
    path('growersurvey/', include('apps.growersurvey.urls')),
    path('notesandupdate/', include('apps.notesandupdate.urls')),
    path('documents/', include('apps.documents.urls')),
    path('contracts/', include('apps.contracts.urls')),
    # sdp
    path('storage/', include('apps.storage.urls')),
    path('processor/', include('apps.processor.urls')),
    path('chat/', include('apps.chat.urls')),
    path('farmsmart/', include('apps.farmsmart.urls')),
    path('growerpayments/', include('apps.growerpayments.urls')),
    path('processor2/', include('apps.processor2.urls')),
    path('processor3/', include('apps.processor3.urls')),
    path('processor4/', include('apps.processor4.urls')),
    path('assistantapp/', include('apps.assistantapp.urls')),
    path('tracemodule/', include('apps.tracemodule.urls')),
    path('warehouse/', include('apps.warehouseManagement.urls')),
    path('quickbooks/', include('apps.quickbooks_integration.urls')),  

    path("select2/", include("django_select2.urls")),  
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Agreeta Solutions (AgFarm Admin Panel)'

apps/accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.utils import timezone
from django.db import connection
from django.contrib.auth.hashers import make_password

from rest_framework.authtoken.models import Token

from phonenumber_field.modelfields import PhoneNumberField

from apps.grower.models import Grower

from django.db.models.signals import post_save
from django.dispatch import receiver




class UserManager(BaseUserManager):
    """Manager for custom user"""

    def create_user(self, first_name, last_name, email, username, password=None):
        """Creates and saves a new user"""
        if not email:
            raise ValueError(_('You must provide an email address'))
        if not username:
            raise ValueError(_('You must provide an username'))

        email = self.normalize_email(email)
        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=email,
            username=username
        )

        #cursor = connection.cursor()
        #cursor.execute("INSERT INTO grower_consultant(name,number,phone,email,created_date,modified_date) VALUES(%s , %s, %s , %s,%s , %s)", [first_name, 8998566565, '+12125585368', email, '2022-03-27 07:44:47.745728', '2022-03-27 07:44:47.745728'])

        #print(repr(password))
        user.set_password(password)
        
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password):
        """Creates and saves a new superuser"""
        user = self.create_user(first_name, last_name, email, username, password)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True

        if user.is_staff is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if user.is_superuser is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')
        user.save(using=self._db)

        return user

    def get_by_natural_key(self, username):
        case_insensitive_username_field = '{}__iexact'.format(self.model.USERNAME_FIELD)
        return self.get(**{case_insensitive_username_field: username})


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that support using email and username"""
    email = models.EmailField(help_text='Email')
    username = models.CharField(max_length=150, unique=True, help_text='Username')
    first_name = models.CharField(max_length=150, blank=True, help_text='First Name')
    last_name = models.CharField(max_length=150, blank=True, help_text='Last Name')
    grower = models.ForeignKey('grower.Grower', on_delete=models.CASCADE, null=True, blank=True)
    role = models.ManyToManyField('Role')
    phone = PhoneNumberField(null = True, blank = True)
    is_consultant = models.BooleanField(default=False)
    is_processor = models.BooleanField(default=False)
    is_processor2 = models.BooleanField(default=False)
    is_processor3 = models.BooleanField(default=False)
    is_distributor = models.BooleanField(default=False)
    is_warehouse_manager = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(auto_now=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    password_raw = models.CharField(max_length=128, unique=False, null=True)
    

    objects = UserManager()
    
  
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        app_label = 'accounts'

    def __str__(self):
        return f'{self.username}'


    #staticPss = "test@123456"

    def save_password(self, password):
        
        self.set_password(password)
        self.save()

    def full_name(self):
        
        return f'{self.first_name} {self.last_name}'

    def logout(self):
        Token.objects.filter(user=self).delete()

    @property
    def token(self):
        token, _ = Token.objects.get_or_create(user=self)
        return token.key

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self)) for field in self.__class__._meta.fields]

    def get_role_perm(self):
        "returns the custom permissions asssigned to the role"
        role_perm = []
        for role in self.role.all():
            for permission in role.permissions.values_list('display'):
                role_perm.append(permission[0])
                #print(role_perm)
        return role_perm

    def get_role(self):
        user_roles_object = self.role.all()
        role_list = [role_data.role for role_data in user_roles_object]

        return role_list

    # def is_super_user(self):
    #     "returns the custom permissions assigned to the role"
    #     role_arr = []
    #     is_super = False
    #     for role in self.role.all():
    #         role_arr.append(role)
    #     role = role_arr[0]
    #     role = str(role)
    #     if(role == "SuperUser"):
    #         is_super = True
    #         #print(is_super)
    #     return is_super


class Role(models.Model):
    """Database model for role"""
    role = models.CharField(max_length=255)
    permissions = models.ManyToManyField('Permission')
    grower = models.ForeignKey(Grower, on_delete=models.CASCADE, null=True, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.role}'


class Permission(models.Model):
    """Database model for permission"""
    name = models.CharField(max_length=255, help_text='e.g. user_management')
    display = models.CharField(max_length=255, help_text='e.g. User Management')


    def __str__(self):
        return f'{self.display}'

class SubSuperUser(models.Model):
    """Database model for Consultant"""
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=10, null=True, blank=True)
    email = models.EmailField(unique=True,
        help_text="ex: cconsultant@gmail.com"
        )
    role = models.ForeignKey('Role', on_delete=models.CASCADE, null=False, blank=False, default=False)
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "SubSuperUser"
        verbose_name_plural = "SubSuperUsers"

    def __str__(self):
        return f'{self.name}'

StatusChoice = (
    ("READ", "READ"),
    ("UNREAD", "UNREAD"),
)

class ShowNotification(models.Model):
    user_id_to_show = models.CharField(max_length=255, null=True, blank=True)
    notification_reason = models.CharField(max_length=255, null=True, blank=True)
    msg = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=255,choices=StatusChoice, null=True, blank=True, default='UNREAD')
    redirect_url = models.TextField(null=True, blank=True)
    added_data_time = models.DateTimeField(auto_now_add=True,null=True, blank=True)

    def __str__(self):
        return f"{self.notification_reason}-{self.msg}"

# 05-04-23
LOG_TYPE_CHOICES = (
    ("User", "User"),
    ("Grower", "Grower"),
    ("Farm", "Farm"),
    ("Field", "Field"),
    ("Storage", "Storage"),
    ("FieldActivity", "FieldActivity"),
    ("GrowerShipment", "GrowerShipment"),
    ("ProcessorUser", "ProcessorUser"),
    ("ClassingReport", "ClassingReport"),
    ("ClassingListTier2", "ClassingListTier2"),
    ("ProcessorUser2", "ProcessorUser2"),
    ("LinkGrowerToProcessor", "LinkGrowerToProcessor"),
    ("ProductionManagement", "ProductionManagement"),
    ("ShipmentManagement", "ShipmentManagement"),
    ("GrowerPayee", "GrowerPayee"),
)
LOG_STATUS_CHOICES = (
    ("Added", "Added"),
    ("Edited", "Edited"),
    ("Password changed", "Password changed"),
    ("Deleted", "Deleted"),
)
LOG_DEVICE_CHOICES = (
    ("Web", "Web"),
    ("App", "App"),
)
class LogTable(models.Model):
    log_type = models.CharField(max_length=250, choices=LOG_TYPE_CHOICES, null=True, blank=True)
    log_status = models.CharField(max_length=250, choices=LOG_STATUS_CHOICES, null=True, blank=True)
    log_idd = models.CharField(max_length=250, null=True, blank=True)
    log_name = models.CharField(max_length=250, null=True, blank=True)
    log_email = models.CharField(max_length=250, null=True, blank=True)
    log_details = models.TextField(null=True, blank=True)
    log_device = models.CharField(max_length=250, choices=LOG_DEVICE_CHOICES, null=True, blank=True)

    action_by_userid = models.CharField(max_length=250, null=True, blank=True)
    action_by_username = models.CharField(max_length=250, null=True, blank=True)
    action_by_email = models.CharField(max_length=250, null=True, blank=True)
    action_by_role = models.CharField(max_length=250, null=True, blank=True)
    action_datetime = models.DateTimeField(auto_now_add=True,null=True, blank=True)


class VersionUpdate(models.Model):
    version = models.CharField(max_length=5, null=True, blank=True)
    release_date = models.DateTimeField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=50, null=True, blank=True)
    updated_users = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"Version {self.version} : {self.release_date}"
    

apps/accounts/templates/accounts/account_filter.html
{% extends "base.html" %} {% load static %} {% block title %} Grower Account List {% endblock title %}
{% load crispy_forms_tags %} {% block content %} {% include 'navbar.html' %}

<div class="main-content">
{% include 'header.html' %}
    <main> <span class="farm headingtop">Search Results</span>
    <form method="get">
    {% csrf_token %}
        {{ filter.form|crispy}}
        <input type="submit" />
    </form>
        <div>
            <div class="bs-example mt-4">
                <div class="table-responsive tblborder">
                    <table class="table">
                        <thead>
                            <tr style="border-bottom: 2px solid #e0e0e0;">
                                <th class="clr2">Name</th>
                                <th class="clr2">Email</th>
                                <th class="clr2">Phone</th>
                                <th class="clr2">Physical Address</th>
                                <th class="clr2">Mailing Address</th>
                                <th class="clr2">CCA Name</th>
                                <th class="clr2">CCA Number</th>
                                <th class="clr2">CCA Phone</th>
                                <th class="clr2">CCA Email</th>
																<th class="clr2">Notes</th>
																<th class="clr2">Date Created</th>
                                <th class="clr2">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for account in filter.qs %}
                            <tr>
                                <td>{{account.name}}</td>
                                <td>{{account.email}}</td>
                                <td>{{account.phone}}</td>
                                <td>{{account.physical_address}}</td>
                                <td>{{account.mailing_address}}</td>
                                <td>{{account.cca_name}}</td>
                                <td>{{account.cca_number}}</td>
                                <td>{{account.cca_email}}</td>
                                <td>{{account.cca_phone}}</td>
																<td>{{account.notes}}</td> 
																<td>{{account.date_created}}</td>
                                <td class="backk1">
                                    <li> <a href="{% url 'accounts-update' account.pk %}"><span class="fas fa-edit"> </span></a></li>
                                    <li> <a href="{% url 'accounts-delete' account.pk %}"><span class="fas fa-trash"
												data-mdb-toggle="modal" data-mdb-target="#exampleModal-delete"></span></a></li>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock content %}

{% comment %} {% extends "base.html" %}

{% block content %}
    <form method="get">
    {% csrf_token %}
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        {{ obj.name }}<br />
    {% endfor %}
{% endblock %} {% endcomment %}

apps/accounts/templates/accounts/add_gallery.html
{% extends "base.html" %}
{% load static %}

{% block title %}

	Upload File

{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
	{% include 'navbar.html' %}
    <div class="main-content">
      {% include 'header.html' %}
	

	<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content m-content">
							<div class="modal-header">
								<h5 class="modal-title foraddd" id="exampleModalLabel">choose FIELD</h5>
								<button type="button" class="btn-close custumclose" data-mdb-dismiss="modal"
									aria-label="Close"></button>
							</div>
							<div class="modal-body">
								<div class="container-fluid">
								<form action="{% url 'gallery-create' %}", method='POST'> 
									{% comment %} <div class="row">
										<div class="col-md-4">
											<select class="addselect">
												<option>Select Grower</option>
												<option>Document</option>
												<option>Photos</option>
											</select>
										</div>
										<div class="col-md-4"></div>
										<div class="col-md-4"></div>
									</div> {% endcomment %}
									{% comment %} <div class="row mt-4">
										<div class="col-md-4">
											{{ form.farm|as_crispy_field }}
										</div>
										
										<div class="col-md-4">
											{{ form.plot|as_crispy_field }}
										</div>
										<div class="col-md-4">
											{{ form.survey_type|as_crispy_field }}
										</div>
									</div> {% endcomment %}
									<div class="row mt-4">
										<div class="col-md-4">
											{{ form.sub_type|as_crispy_field }}
										</div>
										<div class="col-md-4">
											{{ form.image|as_crispy_field }}
										</div>
										<div class="col-md-4">
											{{ form.files|as_crispy_field }}
										</div>
									</div>
								</div>
							</div>
							<div class="modal-footer">
								<button class="btn-inffo">Upload</button><span><button class="btn-inffo2">Cancel</button></span>
								</form>
							</div>
						</div>
					</div>
				</div>
{% endblock content %}

apps/accounts/templates/accounts/user_create.html
 {% extends "base.html" %} 
 {% load static %} 
 {% block title %} Add New User {% endblock title %} 
 {% load crispy_forms_tags %} 
 {% block content %} 
 {% include 'navbar.html' %}
<div class="main-content">
    {% include 'header.html' %}
    <main>
        <span class="farm headingtop">User Registration Form</span>
        <div class="card farm-fields-container">
            <div class="container-fluid">
                <form method="post" class="farm-fields-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.username|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.role|as_crispy_field }}
                            {{ form.is_consultant.as_hidden }}
                        </div>
                        <div class="col-md-4">
                            {{ form.grower|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.password1|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.password2|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-btn-row">
                            <a href="{% url 'user-list' %}" class="btn-close-cancel btn-space">Cancel</a>
                            <input type="submit" class="btn-save-submit" value="Save">
                        </div>
                    </div>
                </form>
            </div>
    </main>
    {% include 'footer.html' %}
    </div>
    
    {% endblock %}

    {% block jquery %}
    <script>
        $(function(){
           //alert('hello');
           $("#id_is_consultant").val('False');
            $("body").on('change', '#id_role', function(e){
                $("#id_is_consultant").val('False');
                //console.log($(this).val());
                var selected_role_ids = $(this).val();
                console.log(selected_role_ids);

                if(selected_role_ids.includes('2'))
                {
                    $("#id_is_consultant").val('True');
                }
                else
                {
                    $("#id_is_consultant").val('False');
                }
            });
        });
    
            
        </script>

    {% endblock jquery %}

apps/accounts/templates/accounts/user_form.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} Add New Account {% endblock title %} 

{% block extrahead %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y3EWVPF7PQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y3EWVPF7PQ');
</script>
{% endblock extrahead %}

{% load crispy_forms_tags %} 
{% block content %} 
{% include 'navbar.html' %}
<div class="main-content">
    {% include 'header.html' %}
    <main>
        <span class="farm headingtop">User Registration Form</span>
        <div class="card farm-fields-container">
            <div class="container-fluid">
                <form method="post" class="farm-fields-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4">
                            {{ form.Role|as_crispy_field }}
                        </div>
                        
                    </div>
                    <div class="row">
                        <div class="form-btn-row">
                            <a href="{% url 'user-list' %}" class="btn-close-cancel btn-space">Cancel</a>
                            <input type="submit" class="btn-save-submit" value="Save">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}
</div>
{% endblock %}
{% block jquery %}
<script>
$(document).ready(function(){
    $("#id_role option[value='2']").remove();
    $("#id_role option[value='4']").remove();
    $("#id_role option[value='9']").remove();
});
</script>
<script>
    $('#User-Management-active').addClass('activeLink');
    $('#User-Management-down').addClass('down');
    $('#User-Management-sub').show();
    $('#user-list').addClass('activeLink active-nav');
</script>
{% endblock jquery %}

apps/accounts/templates/accounts/user_update.html
{% extends "base.html" %} {% load static %} {% block title %} User Update {% endblock title %} 

{% block extrahead %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y3EWVPF7PQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y3EWVPF7PQ');
</script>
{% endblock extrahead %}

{% load crispy_forms_tags %} {% block content %} {% include 'navbar.html' %}
<div class="main-content">
    {% include 'header.html' %}

    <main>
        <span class="farm headingtop">User Update Form</span>

        <div class="card farm-fields-container">
            <div class="container-fluid">

                <form method="post" class="farm-fields-form">

                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4" style="display: none;">
                            {{ form.username|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.email|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        
                        <div class="col-md-4">
                            {{ form.role|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.grower|as_crispy_field }}
                        </div>
                        <!-- <div class="col-md-4">
                            <div id="div_id_password" class="form-group">
                                <label for="id_password" class=" requiredField">
                                       Change Password<span class="asteriskField">*</span>
                                    </label>
                                        <div>
                                             <input type="text" name="password_raw" class="textinput textInput form-control" required="" id="id_password">
                                             <input type="hidden" name="password" class="textinput textInput form-control" required="" id="id_password_hash">
                                        </div>
                            </div>
                        </div> -->

                    </div>
                    
                    <div class="row">
                        <div class="form-btn-row">
                            <a href="{% url 'user-list' %}" class="btn-close-cancel btn-space">Cancel</a>
                            <input type="submit" class="btn-save-submit" value="Save">
                        </div>
                    </div>
                </form>

            </div>
    </main>
    {% include 'footer.html' %}
    </div>
    {% endblock %}
    {% block jquery %}
    <script>
       $('#id_password').on('keyup, input', function(){
           var id_password_val = $(this).val();
          console.log(id_password_val);
          $('#id_password_hash').val(id_password_val);
       });

       $('#id_email').on('keyup, input', function(){
           var id_email_val = $(this).val();
          console.log(id_email_val);
          $('#id_username').val(id_email_val);
       });

       $("#id_role").css({"height":"83px"});
        $(document).ready(function(){
            var sel_id_role = $("#id_role").val();
            if(sel_id_role == 4 || sel_id_role == 2)
            {
                $("#id_role").css({"pointer-events":"none"});
            }
            else
            {
                $("#id_role option[value='2']").remove();
                $("#id_role option[value='4']").remove();
            }
        });
    </script>
    <script>
        $('#User-Management-active').addClass('activeLink');

        $('#User-Management-down').addClass('down');
        $('#User-Management-sub').show();

        $('#user-list').addClass('activeLink active-nav');

      </script>
    {% endblock jquery %}